### ISSUE TITLE
meta-package broken

### ISSUE THREAD

**Issue by alex-eri** [q3aql/amdgpu-firmware-update#2]
firmware-linux-nonfree : Depends: firmware-amd-graphics (= 20190114-1) but 20190319-1 is to be installed

**Comment by q3aql** [comment]
@alex-eri Are you using Debian or Ubuntu?

**Comment by alex-eri** [comment]
Debian.

Meta can be safely removed after installing deps, but needed for future updates.

PS. Thanks for package
